# TCL File Generated by Component Editor 18.1
# Sun Mar 10 20:34:17 GMT 2024
# DO NOT MODIFY


# 
# cosine_custom "cosine_custom" v1.0
#  2024.03.10.20:34:17
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module cosine_custom
# 
set_module_property DESCRIPTION ""
set_module_property NAME cosine_custom
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME cosine_custom
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL cosine
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file cordic.sv SYSTEM_VERILOG PATH cordic/RTLJT/cordic.sv
add_fileset_file cosine.sv SYSTEM_VERILOG PATH cordic/RTLJT/cosine.sv TOP_LEVEL_FILE
add_fileset_file fixed_to_float.sv SYSTEM_VERILOG PATH cordic/RTLJT/fixed_to_float.sv
add_fileset_file float_to_fixed.sv SYSTEM_VERILOG PATH cordic/RTLJT/float_to_fixed.sv
add_fileset_file iteration.sv SYSTEM_VERILOG PATH cordic/RTLJT/iteration.sv


# 
# parameters
# 
add_parameter FRACS INTEGER 22 ""
set_parameter_property FRACS DEFAULT_VALUE 22
set_parameter_property FRACS DISPLAY_NAME FRACS
set_parameter_property FRACS WIDTH ""
set_parameter_property FRACS TYPE INTEGER
set_parameter_property FRACS UNITS None
set_parameter_property FRACS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FRACS DESCRIPTION ""
set_parameter_property FRACS HDL_PARAMETER true
add_parameter INTS INTEGER 1
set_parameter_property INTS DEFAULT_VALUE 1
set_parameter_property INTS DISPLAY_NAME INTS
set_parameter_property INTS TYPE INTEGER
set_parameter_property INTS UNITS None
set_parameter_property INTS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property INTS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point cosine_custom
# 
add_interface cosine_custom nios_custom_instruction end
set_interface_property cosine_custom clockCycle 0
set_interface_property cosine_custom operands 1
set_interface_property cosine_custom ENABLED true
set_interface_property cosine_custom EXPORT_OF ""
set_interface_property cosine_custom PORT_NAME_MAP ""
set_interface_property cosine_custom CMSIS_SVD_VARIABLES ""
set_interface_property cosine_custom SVD_ADDRESS_GROUP ""

add_interface_port cosine_custom clk_en clk_en Input 1
add_interface_port cosine_custom start start Input 1
add_interface_port cosine_custom done done Output 1
add_interface_port cosine_custom floatingPoint_theta dataa Input 32
add_interface_port cosine_custom floatingPoint_result result Output 32
add_interface_port cosine_custom clk clk Input 1
add_interface_port cosine_custom reset reset Input 1

