# TCL File Generated by Component Editor 18.1
# Sun Mar 10 20:27:48 GMT 2024
# DO NOT MODIFY


# 
# cosine_20_iters "cosine_20_iters" v1.0
#  2024.03.10.20:27:48
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module cosine_20_iters
# 
set_module_property DESCRIPTION ""
set_module_property NAME cosine_20_iters
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME cosine_20_iters
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL cosine
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file cordic.sv SYSTEM_VERILOG PATH cordic/RTLJT/cordic.sv
add_fileset_file cosine.sv SYSTEM_VERILOG PATH cordic/RTLJT/cosine.sv TOP_LEVEL_FILE
add_fileset_file fixed_to_float.sv SYSTEM_VERILOG PATH cordic/RTLJT/fixed_to_float.sv
add_fileset_file float_to_fixed.sv SYSTEM_VERILOG PATH cordic/RTLJT/float_to_fixed.sv
add_fileset_file iteration.sv SYSTEM_VERILOG PATH cordic/RTLJT/iteration.sv


# 
# parameters
# 
add_parameter FRACS INTEGER 22
set_parameter_property FRACS DEFAULT_VALUE 22
set_parameter_property FRACS DISPLAY_NAME FRACS
set_parameter_property FRACS TYPE INTEGER
set_parameter_property FRACS UNITS None
set_parameter_property FRACS HDL_PARAMETER true
add_parameter INTS INTEGER 1
set_parameter_property INTS DEFAULT_VALUE 1
set_parameter_property INTS DISPLAY_NAME INTS
set_parameter_property INTS TYPE INTEGER
set_parameter_property INTS UNITS None
set_parameter_property INTS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock nios_custom_instruction end
set_interface_property clock clockCycle 0
set_interface_property clock operands 2
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset nios_custom_instruction end
set_interface_property reset clockCycle 0
set_interface_property reset operands 2
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave done done Output 1
add_interface_port nios_custom_instruction_slave floatingPoint_theta dataa Input 32
add_interface_port nios_custom_instruction_slave floatingPoint_result result Output 32

