# TCL File Generated by Component Editor 18.1
# Sun Mar 17 13:05:52 GMT 2024
# DO NOT MODIFY


# 
# pure_cos "pure_cos" v1.0
#  2024.03.17.13:05:52
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pure_cos
# 
set_module_property DESCRIPTION ""
set_module_property NAME pure_cos
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME pure_cos
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL cosine
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file cordic.sv SYSTEM_VERILOG PATH custom/Optimised/cordic.sv
add_fileset_file cosine.sv SYSTEM_VERILOG PATH custom/Optimised/cosine.sv TOP_LEVEL_FILE
add_fileset_file fixed_to_float.sv SYSTEM_VERILOG PATH custom/Optimised/fixed_to_float.sv
add_fileset_file float_to_fixed.sv SYSTEM_VERILOG PATH custom/Optimised/float_to_fixed.sv
add_fileset_file iteration.sv SYSTEM_VERILOG PATH custom/Optimised/iteration.sv


# 
# parameters
# 
add_parameter FRACS INTEGER 22
set_parameter_property FRACS DEFAULT_VALUE 22
set_parameter_property FRACS DISPLAY_NAME FRACS
set_parameter_property FRACS TYPE INTEGER
set_parameter_property FRACS UNITS None
set_parameter_property FRACS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FRACS HDL_PARAMETER true
add_parameter INTS INTEGER 1
set_parameter_property INTS DEFAULT_VALUE 1
set_parameter_property INTS DISPLAY_NAME INTS
set_parameter_property INTS TYPE INTEGER
set_parameter_property INTS UNITS None
set_parameter_property INTS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property INTS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point pure_cos
# 
add_interface pure_cos nios_custom_instruction end
set_interface_property pure_cos clockCycle 0
set_interface_property pure_cos operands 1
set_interface_property pure_cos ENABLED true
set_interface_property pure_cos EXPORT_OF ""
set_interface_property pure_cos PORT_NAME_MAP ""
set_interface_property pure_cos CMSIS_SVD_VARIABLES ""
set_interface_property pure_cos SVD_ADDRESS_GROUP ""

add_interface_port pure_cos clk_en clk_en Input 1
add_interface_port pure_cos start start Input 1
add_interface_port pure_cos done done Output 1
add_interface_port pure_cos floatingPoint_theta dataa Input 32
add_interface_port pure_cos floatingPoint_result result Output 32
add_interface_port pure_cos clk clk Input 1
add_interface_port pure_cos reset reset Input 1

